### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by jaredpennington** [AdrianHenry15/Plan-It-Organizer#36]
code is in place where it needs to be. The only problem is not everything is showing up. the glowing letters 404 are not visible on the page but exist when you use inspect. If nobody can figure it out we can ask about it in office hours before class or during on tuesday. 

this is the link i took the code from: https://codepen.io/Tibixx/pen/GRKmppz

Changed the top Div AND the h2 have a classname because it was too general and effecting the rest of the site. It works as it is in the code just adding this link as a reference or if something gets deleted and you need it back.

**Comment by AdrianHenry15** [comment]
404 page worked locally for me, styled it. not sure how itll act when deployed
